jakartaee/mail-tck

Jenkinsfile, docker-images/Dockerfile, docker-images/README
Signed-off-by: alwin.joseph <alwin.joseph@oracle.com>
=> use new docker images from eclipse docker hub account

Jenkinsfile
Signed-off-by: alwin.joseph <alwin.joseph@oracle.com>
=> fix user creation in mailserver container

Jenkinsfile, build.xml, docker/build_mailtck.sh, docs/ug/pom.xml, docs/ug/src/main/jbake/content/config.adoc, docs/ug/src/main/jbake/content/tck-packages.inc, docs/ug/src/main/jbake/content/title.adoc, docs/ug/src/main/jbake/templates/footer.ftl
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>
=> mail tck changes for JakartaEE9 release mail-tck2.0.0

Jenkinsfile, docker/run_mailtck.sh
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> Memory configuration for containers

.gitignore, docs/ug/src/main/jbake/content/config.inc, docs/ug/src/main/jbake/content/defns.inc, docs/ug/src/main/jbake/content/intro.inc, docs/ug/src/main/jbake/content/packages.inc, docs/ug/src/main/jbake/content/rebuild.inc, docs/ug/src/main/jbake/content/tck-packages.inc, docs/ug/src/main/jbake/content/using-examples.inc, docs/ug/src/main/jbake/content/using.inc
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> fix cp comments, javax to jakarta

docs/ug/src/main/jbake/content/rebuild.inc
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> Update web-app schema

.gitignore, docker/build_mailtck.sh, docker/run_mailtck.sh, docs/ug/pom.xml, docs/ug/src/main/jbake/jbake.properties, release.xml
same as https://github.com/eclipse-ee4j/jaf-tck/pull/24 but for mail
=> Update TCK user guide to build on JDK11+

Jenkinsfile, docker-images/cts-javamail-base/Dockerfile1, docker-images/cts-javamail-base/Dockerfile2, docker-images/cts-javamail-base/README, docker/run_mailtck.sh
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>
=> update doker image with jdk11

docker/build_mailtck.sh
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> Build TCK using JDK11

Jenkinsfile, release.xml
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> JRuby build fix

Jenkinsfile_2.0.0_bundle
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> Jenkins file for bundled TCK run

build.xml
Signed-off-by: gurunandan.rao@oracle.com <gurunandan.rao@oracle.com>
=> bump up tck version.

Jenkinsfile, build.xml, docker/build_mailtck.sh
Signed-off-by: gurunandan.rao@oracle.com <gurunandan.rao@oracle.com>
=> JDK 11 build.

.gitignore, build.xml, docs/ug/pom.xml, docs/ug/src/main/jbake/assets/_config.yml, docs/ug/src/main/jbake/content/attributes.conf, release.xml, tests/SignatureTest.html
https://github.com/eclipse-ee4j/mail-tck/issues/32
=> update mail tck/user guide version to 2.1/2.1.0

.gitignore, build.xml, docker/build_mailtck.sh
* implementations are not required for building the TCK
* remove obsolete `optimize` compiler flag
* take APIs for build from the module path
* update gitignore
=> clean up the TCK build

lib/ts.jtx
[javatest.batch] Completed running 321 tests.
[javatest.batch] Number of Tests Passed      = 321
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] Number of Tests Not Run     = 0
=> Fix master

docs/ReleaseNotes-2.1.html, docs/index.html, docs/ug/src/main/jbake/content/attributes.conf, release.xml
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> add release notes, index

QuickStart.txt, docs/ReleaseNotes-2.1.html, release.xml
Continues with the work done in https://github.com/eclipse-ee4j/mail-tck/pull/40/
=> Install instructions

docs/ug/src/main/jbake/content/attributes.conf, docs/ug/src/main/jbake/content/title.adoc, lib/ts.jte, lib/ts.pluggability.jte
copyrights, the name of the compatible implementation
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> fix release date,

Jenkinsfile, docker/run_mailtck.sh
update mail and activation implementation jars.
Signed-off-by: gurunandan.rao@oracle.com <gurunandan.rao@oracle.com>
=> update mail and activation implementation jars.

Jenkinsfile, docker/build_mailtck.sh, docker/run_mailtck.sh, lib/ts.jte, lib/ts.pluggability.jte
JDK21 support with security manager disabled.
CI run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/mail-tck-guru/job/security-manager/11/consoleFull
=> JDK21 support with security manager disabled.

Jenkinsfile, build.xml, docker/build_mailtck.sh, docker/run_mailtck.sh, docs/ug/pom.xml, docs/ug/src/main/jbake/content/attributes.conf
4.0.2 service release of Mail TCK with JDK11 build. TCK runs on JDK11,17,21.
=>  4.0.2 service release of Mail TCK with JDK11 build. TCK runs on JDK11,17,21.
